var array = require('./moduloArray')

array.push('yamid')
array.push('maria')
array.push('yago')
array.push('alejandro')
array.push('alvaro')
/*console.log(array)
array.get(3)
array.pop()
console.log(array)
//array.delete(1)
//console.log(array)
array.shif()
console.log(array)
array.unshif()
console.log(array)
*/
console.log(array)
array.unshif('rodrigo')
console.log(array)
array.indexOf('alvarxo')
